apiVersion: v1
kind: Service
metadata:
  name: ms-node-service
spec:
  selector:
    app: ms-node
  ports:
    - protocol: TCP
      port: 80 # This should match the container port in the deployment
      targetPort: 80 # This should match the container port in the deployment
  type: LoadBalancer # Change to NodePort or ClusterIP as needed
