apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '\Ubuntu\home\manan\ms-docker-node-for-user' # Change this to your local project directory
