apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
spec:
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce  # Allows read/write access by a single node
  hostPath:
    path: /mnt/c/D-Drive-Data/Docker/WSL-Working-Projects/ms-docker-node-for-use  # Path on Minikube host
