apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Must match the access mode of the PV
  resources:
    requests:
      storage: 1Gi  # Must match the capacity of the PV
